config/routes.rb
Rails.application.routes.draw do
  resources :intros

end

app/models/intro.rb
class Intro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/intros_controller.rb
class IntrosController < ApplicationController
  before_action :set_intro, only: [:show, :edit, :update, :destroy]

  # GET /intros
  # GET /intros.json
  def index
    @intros = Intro.all
  end

  # GET /intros/1
  # GET /intros/1.json
  def show
  end

  # GET /intros/new
  def new
    @intro = Intro.new
  end

  # GET /intros/1/edit
  def edit
  end

  # POST /intros
  # POST /intros.json
  def create
    @intro = Intro.new(intro_params)

    respond_to do |format|
      if @intro.save
        format.html { redirect_to @intro, notice: 'Intro was successfully created.' }
        format.json { render :show, status: :created, location: @intro }
      else
        format.html { render :new }
        format.json { render json: @intro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intros/1
  # PATCH/PUT /intros/1.json
  def update
    respond_to do |format|
      if @intro.update(intro_params)
        format.html { redirect_to @intro, notice: 'Intro was successfully updated.' }
        format.json { render :show, status: :ok, location: @intro }
      else
        format.html { render :edit }
        format.json { render json: @intro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intros/1
  # DELETE /intros/1.json
  def destroy
    @intro.destroy
    respond_to do |format|
      format.html { redirect_to intros_url, notice: 'Intro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intro
      @intro = Intro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intro_params
      params.require(:intro).permit(:name, :description, :number, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/intros_helper.rb
module IntrosHelper
end

app/views/intros/_form.html.erb
<%= form_for(@intro) do |f| %>
  <% if @intro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intro.errors.count, "error") %> prohibited this intro from being saved:</h2>

      <ul>
      <% @intro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/intros/edit.html.erb
<h1>Editing intro</h1>

<%= render 'form' %>

<%= link_to 'Show', @intro %> |
<%= link_to 'Back', intros_path %>

app/views/intros/index.html.erb
<h1>Listing intros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Number</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intros.each do |intro| %>
      <tr>
        <td><%= intro.name %></td>
        <td><%= intro.description %></td>
        <td><%= intro.number %></td>
        <td><%= intro.note %></td>
        <td><%= link_to 'Show', intro %></td>
        <td><%= link_to 'Edit', edit_intro_path(intro) %></td>
        <td><%= link_to 'Destroy', intro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intro', new_intro_path %>

app/views/intros/new.html.erb
<h1>New intro</h1>

<%= render 'form' %>

<%= link_to 'Back', intros_path %>

app/views/intros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @intro.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @intro.description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @intro.number %>
</p>

<p>
  <strong>Note:</strong>
  <%= @intro.note %>
</p>

<%= link_to 'Edit', edit_intro_path(@intro) %> |
<%= link_to 'Back', intros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>